[project]
name = "gnc_prj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.0",
    "pandas>=2.2.3",
    "pyqt6>=6.8.0",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]
